version: '3.0'

services:
  grafana:
    container_name: 'openobserve'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/openobserve
      - ./provisioning:/etc/grafana/provisioning
